namespace VoiceShipControl
{
    public enum SupportedLanguages
    {
        Afrikaans,              // af-ZA
        Albanian,               // sq-AL
        Amharic,                // am-ET
        Arabic,                 // ar-SA
        Armenian,               // hy-AM
        Azerbaijani,            // az-AZ
        Basque,                 // eu-ES
        Belarusian,             // be-BY
        Bengali,                // bn-IN
        Bosnian,                // bs-BA
        Bulgarian,              // bg-BG
        Catalan,                // ca-ES
        ChineseCantonese,       // yue-Hant-HK
        ChineseMandarinSimplified, // zh-CN
        ChineseMandarinTraditional, // zh-TW
        Croatian,               // hr-HR
        Czech,                  // cs-CZ
        Danish,                 // da-DK
        Dutch,                  // nl-NL
        English,                // en-US
        Estonian,               // et-EE
        Filipino,               // fil-PH
        Finnish,                // fi-FI
        French,                 // fr-FR
        Galician,               // gl-ES
        Georgian,               // ka-GE
        German,                 // de-DE
        Greek,                  // el-GR
        Gujarati,               // gu-IN
        Hebrew,                 // he-IL
        Hindi,                  // hi-IN
        Hungarian,              // hu-HU
        Icelandic,              // is-IS
        Indonesian,             // id-ID
        Italian,                // it-IT
        Japanese,               // ja-JP
        Javanese,               // jv-ID
        Kannada,                // kn-IN
        Kazakh,                 // kk-KZ
        Khmer,                  // km-KH
        Korean,                 // ko-KR
        Kurdish,                // ku-IQ
        Kyrgyz,                 // ky-KG
        Lao,                    // lo-LA
        Latvian,                // lv-LV
        Lithuanian,             // lt-LT
        Luxembourgish,          // lb-LU
        Macedonian,             // mk-MK
        Malay,                  // ms-MY
        Malayalam,              // ml-IN
        Marathi,                // mr-IN
        Mongolian,              // mn-MN
        Nepali,                 // ne-NP
        Norwegian,              // nb-NO
        Oriya,                  // or-IN
        Pashto,                 // ps-AF
        Persian,                // fa-IR
        Polish,                 // pl-PL
        PortugueseBrazil,       // pt-BR
        PortuguesePortugal,     // pt-PT
        Punjabi,                // pa-IN
        Romanian,               // ro-RO
        Russian,                // ru-RU
        Serbian,                // sr-RS
        Sinhala,                // si-LK
        Slovak,                 // sk-SK
        Slovenian,              // sl-SI
        Somali,                 // so-SO
        Spanish,                // es-ES
        Sundanese,              // su-ID
        Swahili,                // sw-TZ
        Swedish,                // sv-SE
        Tamil,                  // ta-IN
        Telugu,                 // te-IN
        Thai,                   // th-TH
        Turkish,                // tr-TR
        Ukrainian,              // uk-UA
        Urdu,                   // ur-PK
        Uzbek,                  // uz-UZ
        Vietnamese,             // vi-VN
        Welsh,                  // cy-GB
        Xhosa,                  // xh-ZA
        Yiddish,                // yi-DE
        Yoruba,                 // yo-NG
        Zulu                    // zu-ZA
    }
}
